### PR TITLE
Documentation & Code Fixes

### PR DESCRIPTION
**Pull request by NidhiHemanth**

### CODE REVIEW

**Comment by NidhiHemanth** [comment]
@sn99

**Comment by sn99** [comment]
@NidhiHemanth You have to comment `Closes` here

**Comment by NidhiHemanth** [comment]
Closes #15

**Comment by NidhiHemanth** [comment]
Closes #15

**Comment by NidhiHemanth** [comment]
@sn99 done and dusted

**Comment by sn99** [comment]
@NidhiHemanth Finally this snapshot ends, ggs

**Pull request merged**
